# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Michael/Desktop/Elektronik/Wintersemester_2022/CHIP/vga_controller/generate/rom_mem_1/rom_mem_1.xci
# IP: The module: 'rom_mem_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Michael/Desktop/Elektronik/Wintersemester_2022/CHIP/vga_controller/generate/rom_mem_1/rom_mem_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_mem_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Michael/Desktop/Elektronik/Wintersemester_2022/CHIP/vga_controller/generate/rom_mem_1/rom_mem_1.xci
# IP: The module: 'rom_mem_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Michael/Desktop/Elektronik/Wintersemester_2022/CHIP/vga_controller/generate/rom_mem_1/rom_mem_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_mem_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
