# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Michael/Desktop/Elektronik/Wintersemester_2022/CHIP/vga_controller/impl/vga_monitor_constrs.xdc

# IP: C:/Users/Michael/Desktop/Elektronik/Wintersemester_2022/CHIP/vga_controller/generate/clk_25Mhz/clk_25Mhz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_25Mhz || ORIG_REF_NAME==clk_25Mhz}]

# IP: C:/Users/Michael/Desktop/Elektronik/Wintersemester_2022/CHIP/vga_controller/generate/rom_mem_1/rom_mem_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_mem_1 || ORIG_REF_NAME==rom_mem_1}]

# IP: C:/Users/Michael/Desktop/Elektronik/Wintersemester_2022/CHIP/vga_controller/generate/rom_mem_2/rom_mem_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_mem_2 || ORIG_REF_NAME==rom_mem_2}]
